export const PATHS = {
  splash: '/splash',
  onboardingEnergy: '/onboarding/energy',
  onboardingReward: '/onboarding/reward',
  onboardingVehicle: '/onboarding/vehicle',
  login: '/login',
  signup: '/signup',
  home: '/',
  aiSchedule: '/ai-schedule',
  participate: '/participate',
  participateConfirm: '/participate/confirm',
  chargingSession: '/charging/session',
  chargingResult: '/charging/result',
  map: '/map',
  stations: '/stations',
  stationDetail: (id: string) => `/stations/${id}`,
  stationReserve: (id: string) => `/stations/${id}/reserve`,
  reservationSuccess: '/reservation/success',
  rewards: '/rewards',
  rewardDetail: (id: string) => `/rewards/${id}`,
  rewardExchange: (id: string) => `/rewards/${id}/exchange`,
  rewardExchangeSuccess: '/rewards/exchange-success',
  rewardHistory: '/rewards/history',
  vehicle: '/vehicle',
  vehicleRegister: '/vehicle/register',
  vehicleDetail: '/vehicle/detail',
  vehicleBatteryHealth: '/vehicle/battery-health',
  notifications: '/notifications',
  notificationDetail: (id: string) => `/notifications/${id}`,
  profile: '/profile',
  impact: '/impact',
  reportMonthly: '/report/monthly',
  settings: '/settings',
  support: '/support',
  supportFaq: '/support/faq',
  supportChat: '/support/chat',
} as const;
